tutors-sdk/tutors

README.md

Having just installed this fresh, the README has a few assumed steps that I am teasing out to be more explicit. I also changed the README to match the new port number and made a clickable link.

Updates to README for clarity

---

pull_request_template.md

A PR Template helps with easier commits from contributors and sets a smoother review process

Adding PR Template

---

pull_request_template.md

Want to make PR example headers smaller, because it looks a bit weird (dividers separates the before / after changes)
---
---

Update markdown of the PR template

---

apps/tutors-html/package.json
apps/tutors-json/package.json

Fix: very small fix to update the email address in package.json app files

fix: updated email in package json app files

---

sites/tutors-home/src/pages/design.astro
sites/tutors-home/src/pages/index.astro

Updated the list of contributors, and updated the link for the tutors components to link to vitebook

Tutors home updates

---

sites/tutors-time-reader/.eslintrc.js
sites/tutors-time-reader/package.json
sites/tutors-time-reader/src/App.svelte
sites/tutors-time-reader/src/components/animations.ts
sites/tutors-time-reader/src/components/cards/Card.svelte
sites/tutors-time-reader/src/components/cards/Image.svelte
sites/tutors-time-reader/src/components/cards/LoggedinStudentCard.svelte
sites/tutors-time-reader/src/components/cards/StudentCard.svelte
sites/tutors-time-reader/src/components/navigators/support/Compact.svelte
sites/tutors-time-reader/src/components/navigators/support/ThemeSwitch.svelte
sites/tutors-time-reader/src/components/navigators/support/TitleCard.svelte
sites/tutors-time-reader/src/components/sheets/calendar-sheet.ts
sites/tutors-time-reader/src/components/sheets/lab-count-sheet.ts
sites/tutors-time-reader/src/components/sheets/lab-sheet.ts
sites/tutors-time-reader/src/environment.ts
sites/tutors-time-reader/src/pages/Live.svelte
sites/tutors-time-reader/src/pages/Presence.svelte
sites/tutors-time-reader/src/pages/Time.svelte
sites/tutors-time-reader/src/pages/support/CalendarTime.svelte
sites/tutors-time-reader/src/pages/support/InstructorCalendarTime.svelte
sites/tutors-time-reader/src/pages/support/InstructorLabTime.svelte
sites/tutors-time-reader/src/pages/support/LabTime.svelte
sites/tutors-time-reader/src/pages/support/NotFound.svelte
sites/tutors-time-reader/src/reader-lib/services/course-service.ts
sites/tutors-time-reader/src/reader-lib/services/metrics-service.ts
sites/tutors-time-reader/src/reader-lib/services/presence-service.ts
sites/tutors-time-reader/src/stores.ts
sites/tutors-time-reader/src/types/global.d.ts

Introducing eslint linting for tutors-time-reader project. I relied on the previous PR related to eslint config. More or less the code is the same and there are a lot of kind of duplicates across several projects. I'm hoping to not create as many bugs as I did before.
- Will fix this issue https://github.com/tutors-sdk/tutors/issues/99
- Commented some of the functions in case if they are not used.

Enable eslint for tutors-time-reader project

---

components/tutors-configs/configs/eslintrc.config.cjs
components/tutors-configs/package.json
package-lock.json
sites/tutors-course-reader/.eslintrc.js
sites/tutors-time-reader/.eslintrc.js

- Common eslint config is introduced
- Two subprojects `sites\tutors-course-reader` & `sites\tutors-time-reader` checked. Seems that linting works as expected.
- Will fix https://github.com/tutors-sdk/tutors/issues/105

Common eslint config

---

package.json

- [X ] The commit message is sensible and easily understood
This now allows us to run npm run accessibility
This gives us the ability to gate on accessibility  changes for CI systems if we so wish and allows contributors check changes locally

Update package.json to include Accessibility Script

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
apps/tutors-time/.eslintrc.js
apps/tutors-time/package.json
apps/tutors-time/src/environment.ts
apps/tutors-time/src/filrebase-utils.ts
apps/tutors-time/src/time-utils.ts
apps/tutors-time/src/tutors-time.ts
apps/tutors-time/tsconfig.json
components/tutors-reader-lib/src/types/store-types.ts
components/tutors-reader-lib/src/utils/firebase-utils.ts
components/tutors-reader-lib/src/utils/lo-utils.ts
components/tutors-reader-lib/src/utils/metrics-utils.ts
package-lock.json
sites/tutors-course-reader/.env.example
sites/tutors-course-reader/src/environment.ts
sites/tutors-course-reader/src/reader-lib/services/analytics-service.ts
sites/tutors-course-reader/src/reader-lib/services/course-service.ts
sites/tutors-course-reader/src/types/global.d.ts
sites/tutors-time-reader/.env.example
sites/tutors-time-reader/src/App.svelte
sites/tutors-time-reader/src/environment.ts
sites/tutors-time-reader/src/pages/AllCourses.svelte
sites/tutors-time-reader/src/reader-lib/services/course-service.ts
sites/tutors-time-reader/src/types/global.d.ts
tsconfig.json

Security update for the tutors store

Tutors store security

---

components/tutors-reader-lib/src/utils/lo-utils.ts
components/tutors-reader-lib/src/utils/markdown-utils.ts
components/tutors-reader-lib/src/utils/search-utils.ts
sites/tutors-course-reader/src/reader-lib/services/metrics-service.ts
sites/tutors-time-reader/src/reader-lib/services/metrics-service.ts

Hello!
I saw your repo and decided to contribute.
In this PR I've fixed several issues that I found by running `npm run check` in `components/tutors-reader-lib`
before:
after:
Sorry that it's so small. Other issues I find challenging for me to fix.

fix: typescript warnings

---

sites/tutors-course-reader/src/navigators/footer/Footer.svelte

chore: version change

---

apps/course/src/lib/navigators/NavUser.svelte
cli/tutors-gen/src/builders/course-builder.ts
cli/tutors-gen/src/builders/lo-types.ts
package-lock.json
packages/tutors-ui/lib/Molecules/Cards/NoteCard.svelte

fixes for note (images), tutors live links + generator issue

---

packages/tutors-ui/lib/Molecules/Breadcrumbs/Breadcrumbs.svelte

feat: migrate breadcrumb to tailwind element

---

apps/course/static/global.css
apps/time/src/routes/time/[courseid]/[...userid]/+page.ts
package-lock.json
packages/tutors-reader-lib/package.json
packages/tutors-reader-lib/src/utils/markdown-utils.ts

feat: copy code blocks in markdown

---

apps/course/netlify.toml

fix: deploy site regardless of content changes

---

apps/course/src/routes/+layout.svelte
packages/tutors-reader-lib/src/models/lab.ts
packages/tutors-reader-lib/src/utils/search-utils.ts
packages/tutors-ui/lib/Molecules/Breadcrumbs/Breadcrumbs.svelte
packages/tutors-ui/lib/Molecules/Cards/Card.svelte
packages/tutors-ui/lib/themes/dyslexia.css
packages/tutors-ui/lib/themes/halloween.css

feat: design updates

---

apps/course/static/manifest.json

fix: install app

---

apps/course/package.json
apps/course/src/app.html
apps/course/src/lib/navigators/LayoutMenu.svelte
apps/course/src/lib/navigators/NavBar.svelte
apps/course/src/lib/navigators/NavUser.svelte
apps/course/src/lib/support/TutorsTerms.svelte
apps/course/src/lib/themebuilder/ThemeBuilder.svelte
apps/course/src/routes/search/[courseid]/+page.svelte
apps/course/tailwind.config.cjs
apps/home/src/routes/+layout.svelte
apps/home/src/routes/+page.svelte
apps/time/src/lib/navigators/NavBar.svelte
apps/time/src/lib/navigators/NavTimeUser.svelte
cli/tutors-html/src/views/components/cards/UnitCard.njk
package-lock.json
packages/tutors-ui/lib/Molecules/Cards/Card.svelte
packages/tutors-ui/lib/Molecules/Cards/CourseCard.svelte
packages/tutors-ui/lib/Molecules/Cards/PrimaryStudentCard.svelte
packages/tutors-ui/lib/Molecules/NavTitle/NavTitle.svelte
packages/tutors-ui/lib/Molecules/NavUser/NavTimeUser.svelte
packages/tutors-ui/lib/Organisms/UnitCard/UnitCard.svelte
packages/tutors-ui/package.json

Feat/skeleton 0.99.5

---

apps/course/src/routes/video/[courseid]/[...loid]/+page.svelte
packages/tutors-ui/lib/Molecules/Cards/VideoCard.svelte

feat: autoplay videos on video page from video card

---

apps/course/src/routes/course/[courseid]/+page.svelte

feat: tutors course reader pwa

---

apps/course/src/routes/course/[courseid]/+page.svelte

fix: scope

---

apps/course/package.json
apps/course/src/lib/navigators/CourseNavigator.svelte
apps/course/src/lib/navigators/NavBar.svelte
apps/home/package.json
apps/time/package.json
package-lock.json
packages/tutors-ui/package.json

feat: skeleton package upgrade

---

apps/course/src/routes/course/[courseid]/+page.svelte

fix: only show install toast on root of course

---

apps/course/src/routes/course/[courseid]/+page.svelte

fix: install bg & manifest

---

README.md
apps/course/package.json
apps/course/src/routes/lab/[courseid]/[...loid]/+page.svelte
packages/tutors-reader-lib/src/models/lab.ts
packages/tutors-ui/lib/Molecules/Footers/Footer.svelte

feat: side labs & sticky mobile lab nav

---

apps/course/package.json
apps/home/package.json
apps/time/package.json
package-lock.json
packages/tutors-ui/package.json

chore: version bumps

---

cli/tutors-html/src/views/components/cards/CardDeck.njk

fix: Card.njk file name in tutors-html

---

package-lock.json
packages/tutors-ui/package.json

fix: netlify adapter to deploy storybook

---

package-lock.json
packages/tutors-ui/.gitignore
packages/tutors-ui/package.json

fix: storybook builds

---

package-lock.json
packages/tutors-ui/package.json

fix: tutors-ui storybook

---

apps/course/.env.example
apps/course/src/environment.ts
packages/tutors-reader-lib/src/services/auth-service.ts

Enables the use of a custom domain with auth0 login services

feat: auth0 custom domain

---

packages/tutors-reader-lib/src/services/presence-service.ts
packages/tutors-reader-lib/src/types/auth-types.ts
packages/tutors-reader-lib/src/utils/firebase-utils.ts

Presence streamline fix

---

apps/course/src/routes/topic/[courseid]/[...loid]/+page.svelte
packages/tutors-ui/lib/Organisms/UnitCard/UnitCard.svelte

fix: sidebar sizing

---

README.md
apps/course/src/lib/support/Loading.svelte
apps/home/package.json
apps/time/package.json
package-lock.json
packages/tutors-ui/lib/Molecules/Cards/TalkCard.svelte
packages/tutors-ui/package.json

urgent fixes

---

.github/holopin.yml
README.md
apps/course/src/lib/support/Loading.svelte
apps/course/svelte.config.js
package-lock.json
packages/tutors-ui/lib/Molecules/Cards/TalkCard.svelte

feat: merge dev to main to diagnose 500 issues

---

apps/course/src/routes/course/[courseid]/+page.svelte

test: remove pwa service worker / install toast

---

apps/course/src/lib/navigators/LayoutMenu.svelte
apps/course/src/lib/themebuilder/ThemeBuilder.svelte
apps/course/src/routes/+layout.svelte
apps/course/src/routes/course/[courseid]/+page.ts
apps/course/src/routes/lab/[courseid]/[...loid]/+page.ts
apps/course/src/routes/note/[courseid]/[...loid]/+page.ts
apps/course/src/routes/talk/[courseid]/[...loid]/+page.svelte
apps/course/src/routes/talk/[courseid]/[...loid]/+page.ts
apps/course/src/routes/topic/[courseid]/[...loid]/+page.ts
apps/course/src/routes/topic/[courseid]/[...loid]/topic.svelte
packages/tutors-ui/lib/Atoms/Icon/Icon.svelte

fix: enable ssr & dark mode

---

apps/course/src/routes/course/[courseid]/+page.svelte
cli/tutors-gen/package.json
cli/tutors-gen/src/builders/course-builder.ts
cli/tutors-gen/src/tutors-gen.ts
cli/tutors-gen/src/utils/lr-utils.ts
cli/tutors-gen/src/utils/utils.ts

fix: ssr on course pages

---

apps/course/src/routes/topic/[courseid]/[...loid]/topic.svelte

fix: loading animation on topic

---

apps/home/.prettierrc
apps/home/src/lib/DeveloperExperience.svelte
apps/home/src/lib/EducatorExperience.svelte
apps/home/src/lib/ExperienceCard.svelte
apps/home/src/lib/LearnerExperience.svelte
apps/home/src/routes/+page.svelte

fix experience links + reorganise into cards

---

apps/course/src/routes/lab/[courseid]/[...loid]/+page.svelte
apps/course/static/global.css
cli/tutors-gen/package.json
cli/tutors-gen/src/builders/course-builder.ts
cli/tutors-gen/src/tutors-gen.ts

fix: lab steps

---

apps/course/package.json
apps/course/src/lib/navigators/LayoutMenu.svelte
apps/course/src/routes/+layout.svelte
apps/course/src/routes/lab/[courseid]/[...loid]/+page.svelte
apps/course/src/routes/lab/[courseid]/[...loid]/+page.ts
apps/course/src/routes/tutors-startup.ts
apps/course/svelte.config.js
apps/course/tailwind.config.cjs
package-lock.json
packages/tutors-reader-lib/package.json
packages/tutors-reader-lib/src/types/md-types.ts
packages/tutors-reader-lib/src/utils/markdown-utils.ts

Reenable kaytex support + some tidy up re plugins/warnings

---

app/src/lib/home/DeveloperExperience.svelte
app/src/lib/home/EducatorExperience.svelte
app/src/lib/home/ExperienceCard.svelte
app/src/lib/home/LearnerExperience.svelte
app/src/routes/(home)/+page.svelte

fix: homepage links

---

app/src/lib/components/Navigation/Primary/LayoutMenu/NavigationPrimaryLayoutMenu.svelte
app/src/lib/components/Navigation/Primary/LayoutMenu/index.ts
app/src/lib/components/Navigation/Primary/UserMenu/NavigationPrimaryUserMenu.svelte
app/src/lib/components/Navigation/Primary/UserMenu/index.ts
app/src/lib/components/index.ts
app/src/routes/+layout.svelte

feat: primary nav menus

---

app/cypress/support/commands.ts
doc/reference-course/cypress/e2e/tutorsHtmlGenerator.cy.ts
doc/reference-course/cypress/support/commands.ts

- [x ] The commit message is sensible and easily understood

fix: tutors html generator has been fixed now to run

---

.github/workflows/ci.yml
package-lock.json
package.json

* feat: add cypress to package (78635272b1541e5e207ab15f90019b70ee48c34d)
* fix: cypress (6763dcdd694e4513d8d39b188248b6b8401986de)
* fix: update cypress as dev deps (40d7d6aabd3fdbdaf63bf0e4bb422e85f89f0656)
* fix: capitalization (0936b9d9d62941829a53cdb3a3cbb8c31e2243d3)
* fix: revert (a55e2c1d69dc28f21c3e70373d70d4181ad0d9ff)
* test: build gen-lib also (c66b1153b89afe2f3e3ed969e516633f87c40198)
* test: use cypress runner (c2bf52d90b6f2900ac3a2211cdf4ca58adea0559)

test: build gen-lib also

---

app/src/lib/services/presence.ts

* fix: hide self from online list (1e6241fd0b914fdaaacf01174643ff866e38fcdc)

fix: hide self from online list

---

app/src/lib/services/course.ts
app/src/routes/(auth)/dashboard/+page.svelte

* fix: accept non-netlify domains for courses (9a71b84a7a7833fc21848de950740aab98fd5859)
* fix: sort dashboard by most recently accessed (00db0d53a9261ff5bd1d763b09a7a861f17f1c6a)

Fix: accept non-netlify domains for courses & sort dashboard by most recently accessed

---

app/cypress/support/commands.ts

- [x ] The commit message is sensible and easily understood
- [x ] Docs have been added / updated (for bug fixes / features where relevant)
Bug Fix
A fix for the cypress test in testing the toc and checking for undefined on a page
* fix: cypress fix for toc and check for undefined on the page (589de598d15cdb37f1f86d4500d5c2c7271ae473)

fix: cypress fix for toc and check for undefined on the page

---

app/src/routes/(auth)/auth/+page.svelte
app/src/routes/(auth)/auth/login.svelte
app/src/routes/(auth)/auth/terms.svelte

fix: auth page design

---

app/src/routes/(auth)/dashboard/+page.svelte
package-lock.json

- [x ] The commit message is sensible and easily understood
- [x ] Docs have been added / updated (for bug fixes / features where relevant)
Bug fix
undefined is appearing if name has not been filled in github, this uses user name if no name
* fix: undefined name appearing on dashboard (2df53570caa5d9b520b703afbedeb85d55d3dee1)

fix: undefined name appearing on dashboard

---

app/src/lib/ui/navigators/profiles/CourseProfileMenu.svelte
app/src/routes/(auth)/dashboard/+page.svelte

- [ x] The commit message is sensible and easily understood
- [x ] Docs have been added / updated (for bug fixes / features where relevant)
Bug fix
Remove undefined when there is no name, to use username
* fix: username will be used if name is undefined (0439ad9eaa58efd3a8cc3c55d41bafb03fa9b5f2)

fix: username will be used if name is undefined

---

app/src/lib/ui/icons/Breadcrumbs.svelte
app/src/lib/ui/icons/Icon.svelte
app/src/lib/ui/icons/IconBar.svelte
app/src/lib/ui/learning-objects/content/Talk.svelte

Skeleton tips causing issues. Revert to 'title' attribute on links

fix: remove skeleton tooltips

---

app/src/lib/services/types/metrics.ts
app/src/lib/ui/time/PrimaryStudentCard.svelte

- [ x] The commit message is sensible and easily understood
- [ x] Tests for the changes have been added (for bug fixes / features where relevant)
- [ x] Docs have been added / updated (for bug fixes / features where relevant)
Bug fix
If name is undefined then presence display name defaults to email
* fix: remove undefined from presence replaced with email if no name (a7b98dc68a32ac231d8b1479ade50c7b32677eb6)

fix: remove undefined from presence replaced with email if no name

---

app/package.json

Bug fix, add vite-plugin-svelte in the app directory.
This PR realate fix/add-vite-plugin-svelte

Add vite plugin svelte in app directory

---

app/cypress/e2e/tutorsReader.cy.ts
app/cypress/support/commands.ts
app/package.json

Bug fix and additional login test
fix/cypress-tests

Fix the cypress test failing and add new login test

---

src/lib/services/models/live-lab.ts
src/lib/stores.ts
src/lib/ui/icons/themes/fluent-icons.ts
src/lib/ui/icons/themes/halloween-icons.ts
src/lib/ui/icons/themes/hero-icons.ts
src/lib/ui/navigators/EditCoursButton.svelte
src/lib/ui/navigators/SecondaryNavigator.svelte
src/lib/ui/navigators/buttons/EditCoursButton.svelte
src/routes/(course-reader)/lab/[courseid]/[...loid]/+page.ts

- [ x The commit message is sensible and easily understood
- [ x] Docs have been added / updated (for bug fixes / features where relevant)
New Feature - documented here:
- <https://tutors.dev/course/tutors-reference-manual#edit-course-button>

Edit button for open source course

---

src/lib/services/presence.ts
src/lib/ui/navigators/Links.svelte
src/routes/(time)/simulate/+page.svelte

Information in simulator window + link to simulator on home page

---

src/lib/ui/icons/Icon.svelte
src/lib/ui/icons/IconBar.svelte
src/lib/ui/icons/themes/NetlifyIcon.svelte
src/lib/ui/icons/themes/SetuIcon.svelte
src/lib/ui/icons/themes/TutorsIcon.svelte
src/lib/ui/navigators/buttons/EditCoursButton.svelte
src/lib/ui/navigators/buttons/InfoButton.svelte
src/lib/ui/navigators/buttons/TocButton.svelte
src/lib/ui/navigators/footers/Footer.svelte
src/lib/ui/navigators/footers/TutorsVersion.svelte
tailwind.config.ts

Remove violations as reported by [IBM Equal Access Accessibility Checker](https://chromewebstore.google.com/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp)

#672 accessibility audit

---

src/lib/ui/navigators/footers/TutorsMessage.svelte

Added dark:prose-invert to TutorsMessage component to fix issue of poor contrast in dark mode for text in footer.

Add dark:prose-invert to improve readability in dark mode

---

src/routes/(time)/simulate/generateStudent.ts
src/routes/(time)/simulate/presence-simulator.ts

Edits simulator so that images don't repeat as often
650c684868b2500b4452444554766dc0d3394bb3

Simulator improvement

---

src/lib/ui/time/supabase/analytics/lab-heat-map.ts
src/lib/ui/time/supabase/analytics/topic-heat-map.ts
src/lib/ui/time/supabase/charts/boxplot-chart.ts
src/lib/ui/time/supabase/charts/calendar-chart.ts
src/routes/(time)/next-time/[courseid]/+page.svelte

Bug fix: remove console.log and correct the name in the dropdown in next analytics time

Remove console log and correct name for lab pie chart

---

src/lib/ui/time/supabase/analytics/lab-heat-map.ts
src/lib/ui/time/supabase/analytics/topic-heat-map.ts
src/lib/ui/time/supabase/charts/calendar-chart.ts
src/lib/ui/time/supabase/charts/heatmap-chart.ts

Bug fix for heatmap sizing and displaying full name in labs

Fix for heatmap size and lab names

---

src/lib/ui/time/supabase/charts/heatmap-chart.ts
src/routes/(time)/next-time/[courseid]/+page.svelte

Update the style of time to be more intuative

---

src/lib/ui/time/supabase/analytics/lab-heat-map.ts
src/lib/ui/time/supabase/analytics/topic-heat-map.ts

Bug fix, it was checking for a title that didn't exist

Update the grid size for topics heatmap

---

src/lib/ui/time/supabase/analytics/lab-heat-map.ts
src/lib/ui/time/supabase/analytics/topic-heat-map.ts
src/routes/(time)/next-time/[courseid]/+page.svelte

feature: Add sort for lab and topics heatmap

Add sort for lab and topics heatmap

---

src/lib/services/utils/supabase-utils.ts
src/lib/ui/time/supabase/analytics/lab-heat-map.ts
src/lib/ui/time/supabase/analytics/topic-heat-map.ts
src/lib/ui/time/supabase/charts/heatmap-chart.ts
src/lib/ui/time/supabase/views/InstructorLabView.svelte

Bug fix, for heatmap size for a lot of users and the increment of the pageloads in calendar

Fix the size of heatmap and pageloads increment

---

src/lib/services/utils/supabase-utils.ts
src/lib/ui/time/supabase/analytics/calendar.ts
src/lib/ui/time/supabase/charts/calendar-chart.ts
src/lib/ui/time/supabase/views/CalendarView.svelte
src/lib/ui/time/supabase/views/InstructorCalendarView.svelte
src/routes/(time)/next-time/[courseid]/+page.svelte
src/routes/(time)/next-time/[courseid]/+page.ts

feature: Implement a median calendar for a student to get an idea of other students work rate

Implement new median calendar feature

---

src/lib/services/utils/supabase-utils.ts
src/lib/ui/time/supabase/analytics/calendar.ts
src/lib/ui/time/supabase/analytics/lab-heat-map.ts
src/lib/ui/time/supabase/analytics/topic-heat-map.ts
src/lib/ui/time/supabase/charts/calendar-chart.ts
src/lib/ui/time/supabase/views/CalendarView.svelte
src/lib/ui/time/supabase/views/InstructorCalendarView.svelte

Bug fixs: update calendar size, remove inactive time check, remove calls to github api

Update calendar size and remove calls to github api and inactive time

---

src/lib/services/utils/supabase-utils.ts

Bug fix
When a user is not logged in, added a null check

Fix if a person is not logged in

---

src/lib/ui/time/supabase/charts/heatmap-chart.ts
src/lib/ui/time/supabase/views/HeatMapChart.svelte
src/lib/ui/time/supabase/views/InstructorLabViewBoxPlot.svelte
src/lib/ui/time/supabase/views/InstructorTopicViewBoxPlot.svelte

Bug fix
Fix for layout of charts for small numbers of students

Fix the layout of charts for small numbers

---

src/lib/ui/themes/card/Card.svelte
src/lib/ui/themes/menu/DarkModeToggle.svelte
src/lib/ui/themes/menu/LayoutToggle.svelte

This PR implements the compact layout option, integrated with the new skeleton 3 card theming format.

implement compact layout

---

src/lib/ui/learning-objects/content/Lab.svelte

move lab nav to the bottom of the view in mobile + some other adjustments for mobile

---

src/lib/ui/navigators/LayoutMenu.svelte
src/lib/ui/navigators/MainNavigator.svelte

Updated order of layout menu options to resolve a background transparency issue with theme/code style drop downs

Update layout menu order

---

src/lib/ui/navigators/LayoutMenu.svelte
src/routes/(home)/Links.svelte

Added an "Appearance" label above the light/dark mode options to ensure consistency with the rest of the layout menu and to make it clearer what the option represents

add layout appearance heading

---

src/routes/+layout.svelte

revert to tutors theme

---

package.json

correct version update
